title: Blog Education
description: A bold typographic theme inspired by Swiss design.
social_link: twitter
social_username: broccolini
github_repo: edu
github_username: fatchurrozaq
theme_color: black
remote_theme: internet-de-france/swiss
baseurl: /edu
jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration
  homepage: pages
defaults:
  - scope:
      path: ''
      type: pages
    values:
      category_name: ''
  - scope:
      path: ''
      type: posts
    values:
      categories: ''
remote_theme_layouts:
  - ''
  - default
  - page
  - post
  - home
  - category_index
social_links:
  - twitter
  - instagram
  - medium
  - dribbble
theme_colors:
  - black
  - blue
  - gray
  - magenta
  - orange
  - red
  - white
  - yellow
